### ISSUE TITLE
Pydantic error when starting master

### ISSUE THREAD

**Issue by Erethon** [nix-community/buildbot-nix#270]
I'm opening and closing this issue immediately after [discussing it on matrix](https://matrix.to/#/!jovugA1YVANemdLs:thalheim.io/$vLJ0jBFuXUuVvZBaqqHKuSkfeqndkSzBa6sK5CPw-AE?via=thalheim.io&via=matrix.org&via=helsinki-systems.de), so that it's searchable in case it happens to other people too.

After upgrading from an older version of buildbot-nix (around May 2024) to the current latest one (September 2024), the master process failed to start with:

```
2024-09-03T00:13:38+0200 [twisted.logger._global#warn] /nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/pydantic/_internal/_config.py:334: builtins.UserWarning: Valid config keys have changed in V2
        * 'fields' has been removed
2024-09-03T00:13:38+0200 [-] while starting BuildMaster
        Traceback (most recent call last):
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
            current.result = callback(  # type: ignore[misc]
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/twisted/internet/defer.py", line 1949, in _gotResultInlineCallbacks
            _inlineCallbacks(r, gen, status, context)
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/twisted/internet/defer.py", line 1999, in _inlineCallbacks
            result = context.run(
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/twisted/python/failure.py", line 519, in throwExceptionIntoGenerator
            return g.throw(self.value.with_traceback(self.tb))
        --- <exception caught here> ---
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/buildbot/master.py", line 250, in startService
            self.config = yield threads.deferToThreadPool(
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/twisted/python/threadpool.py", line 269, in inContext
            result = inContext.theWork()  # type: ignore[attr-defined]
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/twisted/python/threadpool.py", line 285, in <lambda>
            inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
            return func(*args, **kw)
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/buildbot/config/master.py", line 124, in loadConfig
            config = MasterConfig.loadFromDict(config_dict, filename)
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/buildbot/config/master.py", line 261, in loadFromDict
            config.run_configurators(filename, config_dict)
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/buildbot/config/master.py", line 292, in run_configurators
            interfaces.IConfigurator(configurator).configure(config_dict)
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/buildbot_nix/__init__.py", line 929, in configure
            projects += backend.load_projects()
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/buildbot_nix/github_projects.py", line 621, in load_projects
            model_validate_project_cache(RepoData, self.config.project_cache_file),
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/buildbot_nix/common.py", line 169, in model_validate_project_cache
            cls.model_validate(data) for data in json.loads(project_cache_file.read_text())
          File "/nix/store/sj4hwn82jzsyhch67b189bll7rrqx3ya-python3-3.12.4-env/lib/python3.12/site-packages/pydantic/main.py", line 551, in model_validate
            return cls.__pydantic_validator__.validate_python(
        pydantic_core._pydantic_core.ValidationError: 1 validation error for RepoData
        installation_id
          Field required [type=missing, input_value={'id': 601580014, 'node_i...e': True, 'pull': True}}, input_type=dict]
            For further information visit https://errors.pydantic.dev/2.7/v/missing
```

This was caused because `installation_id` was missing from the project cache file. Deleting `/var/lib/buildbot/github-project-cache-v1.json` and restarting fixed the issue.

**Comment by Erethon** [comment]
As mentioned, closing issue immediately!
