### ISSUE TITLE
Buildbot Frontend not reachable

### ISSUE THREAD

**Issue by malikwirin** [nix-community/buildbot-nix#352]
My configuration isn't based on the [clan infra](https://git.clan.lol/clan/clan-infra/src/branch/main/modules/buildbot.nix). But I realized that they are very similar.

``` nix
{ config, lib, ... }:

let
  sopsCfg = config.sops;
  domain = config.networking.domain;
in
{
  services = {
    buildbot-nix.master = {
      enable = true;
      domain = "buildbot.${domain}";

      workersFile = sopsCfg.templates."buildbot-workers.json".path;
      admins = [ "malik" ];
      outputsPath = "/var/www/buildbot/nix-outputs";

      authBackend = "gitea";
      gitea = {
        enable = true;
        tokenFile = sopsCfg.secrets."codeberg-token".path;
        instanceUrl = "https://codeberg.org";
        oauthId = "redacted";
        oauthSecretFile = sopsCfg.secrets."cb-buildbot-secret".path;
        webhookSecretFile = sopsCfg.secrets."buildbot-webhook".path;
        topic = "build-with-buildbot";
      };
    };

    buildbot-master = {
      buildbotUrl = lib.mkForce "https://${config.services.buildbot-nix.master.domain}";
    };
    
    nginx.virtualHosts."${config.services.buildbot-nix.master.domain}" = {
      useACMEHost = domain;
      addSSL = true;
    };
  };
}
```

But I always see the following instead of the buildbot frontend when trying to.
![Bildschirmfoto vom 2024-12-14 18-34-23](https://github.com/user-attachments/assets/fa8bbadd-ad88-41d5-94b1-dd16fbd7b0b1)
Could this be related to [harmonia#481](https://github.com/nix-community/harmonia/issues/481)?

**Comment by Mic92** [comment]
Check `journalctl -u buildbot-master -f` for details.

**Comment by MagicRB** [comment]
For context, `503` means the gateway, i.e. the backend couldn't be reached. The Nginx config contains a `proxy_pass` directive and it will throw a `503` if the port is unreachable, specifically when it returns a `Connection Refused`, on a `Connection Timeout` you get a `504`

**Comment by malikwirin** [comment]
> Check `journalctl -u buildbot-master -f` for logs.

```
Dez 16 10:05:10 hetzbox systemd[1]: Starting Buildbot Continuous Integration Server....
Dez 16 10:05:14 hetzbox buildbot-master-pre-start[488717]: updating existing installation
Dez 16 10:05:14 hetzbox buildbot-master-pre-start[488717]: not touching existing buildbot.tac
Dez 16 10:05:14 hetzbox buildbot-master-pre-start[488717]: creating buildbot.tac.new instead
Dez 16 10:05:14 hetzbox buildbot-master-pre-start[488717]: creating /var/lib/buildbot/master/master.cfg.sample
Dez 16 10:05:14 hetzbox buildbot-master-pre-start[488717]: creating database (postgresql://@/buildbot)
Dez 16 10:05:14 hetzbox buildbot-master-pre-start[488717]: buildmaster configured in /var/lib/buildbot/master
Dez 16 10:05:15 hetzbox systemd[1]: Started Buildbot Continuous Integration Server..
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:15+0100 [-] Loading /var/lib/buildbot/master/buildbot.tac...
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [-] Loaded.
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 24.7.0 (/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/bin/python3.12 3.12.7) starting up.
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [-] Starting BuildMaster -- buildbot.version: 4.1.0
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [-] Loading configuration from '/nix/store/9v7k84jr8sniapsdq0srgxknwn1024h0-master.cfg'
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [twisted.logger._global#warn] /nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/pydantic/_internal/_config.py:341: builtins.UserWarning: Valid config keys have changed in V2:
Dez 16 10:05:18 hetzbox twistd[488723]:         * 'fields' has been removed
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [-] while starting BuildMaster
Dez 16 10:05:18 hetzbox twistd[488723]:         Traceback (most recent call last):
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/twisted/internet/defer.py", line 1074, in _runCallbacks
Dez 16 10:05:18 hetzbox twistd[488723]:             current.result = callback(  # type: ignore[misc]
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/twisted/internet/defer.py", line 1960, in _gotResultInlineCallbacks
Dez 16 10:05:18 hetzbox twistd[488723]:             _inlineCallbacks(r, gen, status, context)
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/twisted/internet/defer.py", line 2010, in _inlineCallbacks
Dez 16 10:05:18 hetzbox twistd[488723]:             result = context.run(
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/twisted/python/failure.py", line 549, in throwExceptionIntoGenerator
Dez 16 10:05:18 hetzbox twistd[488723]:             return g.throw(self.value.with_traceback(self.tb))
Dez 16 10:05:18 hetzbox twistd[488723]:         --- <exception caught here> ---
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/buildbot/master.py", line 252, in startService
Dez 16 10:05:18 hetzbox twistd[488723]:             self.config = yield threads.deferToThreadPool(
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/twisted/python/threadpool.py", line 269, in inContext
Dez 16 10:05:18 hetzbox twistd[488723]:             result = inContext.theWork()  # type: ignore[attr-defined]
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/twisted/python/threadpool.py", line 285, in <lambda>
Dez 16 10:05:18 hetzbox twistd[488723]:             inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
Dez 16 10:05:18 hetzbox twistd[488723]:             return self.currentContext().callWithContext(ctx, func, *args, **kw)
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
Dez 16 10:05:18 hetzbox twistd[488723]:             return func(*args, **kw)
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/buildbot/config/master.py", line 133, in loadConfig
Dez 16 10:05:18 hetzbox twistd[488723]:             config = MasterConfig.loadFromDict(config_dict, filename)
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/buildbot/config/master.py", line 270, in loadFromDict
Dez 16 10:05:18 hetzbox twistd[488723]:             config.run_configurators(filename, config_dict)
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/buildbot/config/master.py", line 301, in run_configurators
Dez 16 10:05:18 hetzbox twistd[488723]:             interfaces.IConfigurator(configurator).configure(config_dict)
Dez 16 10:05:18 hetzbox twistd[488723]:           File "/nix/store/n5qg1m1d7jqcvg7da7vnrc3waqz7s8ny-python3-3.12.7-env/lib/python3.12/site-packages/buildbot_nix/__init__.py", line 1824, in configure
Dez 16 10:05:18 hetzbox twistd[488723]:             reload_builder = backend.create_reload_builder([worker_names[0]])
Dez 16 10:05:18 hetzbox twistd[488723]:         builtins.IndexError: list index out of range
Dez 16 10:05:18 hetzbox twistd[488723]:
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [-] BuildMaster startup failed
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [-] BuildMaster is stopped
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [twisted.internet.base#info] Main loop terminated.
Dez 16 10:05:18 hetzbox twistd[488723]: 2024-12-16T10:05:18+0100 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
Dez 16 10:05:19 hetzbox systemd[1]: buildbot-master.service: Deactivated successfully.
Dez 16 10:05:19 hetzbox systemd[1]: buildbot-master.service: Consumed 7.934s CPU time, 120.5M memory peak, 39.4M read from disk.
```

**Comment by MagicRB** [comment]
I'll take a look at this later today, now I know where the bug is probably

**Comment by Mic92** [comment]
Have you not configured any workers by chance?

**Comment by malikwirin** [comment]
> Have you not configured any workers by chance?

The Buildbot worker is also failing with reference to [twisted](https://github.com/twisted/twisted).

```
Dez 16 10:23:09 hetzbox twistd[489059]:     endpoint = clientFromString(reactor, connection_string)
Dez 16 10:23:09 hetzbox twistd[489059]:   File "/nix/store/165y4y7b2s5nsyznqgiv4dnxb7nnndb8-python3-3.12.7-env/lib/python3.12/site-packages/twisted/internet/endpoints.py", line 2133, in clientFromString
Dez 16 10:23:09 hetzbox twistd[489059]:     plugin = _matchPluginToPrefix(
Dez 16 10:23:09 hetzbox twistd[489059]:   File "/nix/store/165y4y7b2s5nsyznqgiv4dnxb7nnndb8-python3-3.12.7-env/lib/python3.12/site-packages/twisted/internet/endpoints.py", line 1737, in _matchPluginToPrefix
Dez 16 10:23:09 hetzbox twistd[489059]:     raise ValueError(f"Unknown endpoint type: '{endpointType}'")
Dez 16 10:23:09 hetzbox twistd[489059]: builtins.ValueError: Unknown endpoint type: 'buildbot.$topdomain'
Dez 16 10:23:09 hetzbox twistd[489059]: Starting worker hetzbox-000
Dez 16 10:23:09 hetzbox twistd[489059]: Failed to load application: Unknown endpoint type: 'buildbot.$topdomain'
Dez 16 10:23:09 hetzbox systemd[1]: buildbot-worker.service: Main process exited, code=exited, status=1/FAILURE
Dez 16 10:23:09 hetzbox systemd[1]: buildbot-worker.service: Failed with result 'exit-code'.
```
I obfuscated the domain. But because its a free domain provider (for not much longer) I witnessed some instabilities in resolving the name.

The worker is configured like this:
``` nix
{ config, ... }:

let
  masterCfg = config.services.buildbot-nix.master;
  masterPort = config.services.buildbot-master.port;
in
{
  services.buildbot-nix.worker = {
    enable = true;
    name = config.networking.hostName;
    masterUrl = "${masterCfg.domain}:${(toString masterPort)}";
    workerPasswordFile = config.sops.secrets."hetzbox-buildbot-worker-password".path;
  };
}
```

**Comment by Mic92** [comment]
I mean in your `buildbot-workers.json` file.

**Comment by malikwirin** [comment]
> I mean in your `buildbot-workers.json` file.

The buildbot-workers.json is configured as a sops template. Could users and groups be wrong?

``` nix
{ inputs, config, ... }:

let
  hostName = config.networking.hostName;
  cfg = config.sops;
  bb-master-user = config.users.users.buildbot;
  bb-worker-user = config.users.users.buildbot-worker;
  buildbot-group = bb-master-user.group;
  bbMasterPort = config.services.buildbot-master.port;
in
{
  sops = {
    secrets = {
      codeberg-token = {
        group = buildbot-group;
      };
      cb-buildbot-secret = {
        owner = bb-master-user.name;
      };
      buildbot-webhook = {
        owner = bb-master-user.name;
      };
      hetzbox-buildbot-worker-password = {
        owner = bb-worker-user.name;
        group = buildbot-group;
      };
    };

    templates = {
      "buildbot-workers.json" = {
        content = ''
          [
            {
              "name": "${hostName}",
              "password": "${cfg.placeholder.hetzbox-buildbot-worker-password}",
              "host": "${hostName}",
              "port": ${(toString bbMasterPort)}
            }
          ]
        '';
        owner = bb-master-user.name;
      };
    };
  };
}
```

**Comment by Mic92** [comment]
It's called "pass" instead of password and there is no `host` or `port` in this file.
I added some model validation here: https://github.com/nix-community/buildbot-nix/pull/356/files
However this doesn't explain the error yet, you were seeing.

**Comment by Mic92** [comment]
Use this as a template: https://github.com/nix-community/buildbot-nix/blob/8dc24d5432b02a44b34f42916676b60b62dd3478/examples/master.nix#L15

**Comment by malikwirin** [comment]
> It's called "pass" instead of password and there is no `host` or `port` in this file. I added some model validation here: https://github.com/nix-community/buildbot-nix/pull/356/files However this doesn't explain the error yet, you were seeing. Ah you need to specify number of cores as well in the "cores" field.

Thanks a lot. My issue is resolved as the frontend is now reachable. I cannot remember where I got the wrong workers.json config from.

I am not really sure what cores means in this context. So i took half the number of available threads.

**Comment by Mic92** [comment]
> > It's called "pass" instead of password and there is no `host` or `port` in this file. I added some model validation here: https://github.com/nix-community/buildbot-nix/pull/356/files However this doesn't explain the error yet, you were seeing. Ah you need to specify number of cores as well in the "cores" field.
> 
> Thanks a lot. My issue is resolved as the frontend is now reachable. I cannot remember where I got the wrong workers.json config from.
> 
> I am not really sure what cores means in this context. So i took half the number of available threads.

It's number of concurrent build jobs effectively. If you allocate less, than you will see some errors in your buildbot worker because half the worker instances won't be able to connect.
