### ISSUE TITLE
Exception when reporting status in the buildbot UI

### ISSUE THREAD

**Issue by MagicRB** [nix-community/buildbot-nix#363]
```
2024-12-29T14:31:42+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/nix/store/3ix3c6m62qjj6abfxlkxz6nxp6dp1nnk-python3-3.12.7-env/lib/python3.12/site-packages/twisted/internet/defer.py", line 1960, in _gotResultInlineCallbacks
	    _inlineCallbacks(r, gen, status, context)
	  File "/nix/store/3ix3c6m62qjj6abfxlkxz6nxp6dp1nnk-python3-3.12.7-env/lib/python3.12/site-packages/twisted/internet/defer.py", line 2010, in _inlineCallbacks
	    result = context.run(
	  File "/nix/store/3ix3c6m62qjj6abfxlkxz6nxp6dp1nnk-python3-3.12.7-env/lib/python3.12/site-packages/twisted/python/failure.py", line 549, in throwExceptionIntoGenerator
	    return g.throw(self.value.with_traceback(self.tb))
	  File "/nix/store/3ix3c6m62qjj6abfxlkxz6nxp6dp1nnk-python3-3.12.7-env/lib/python3.12/site-packages/buildbot/process/build.py", line 629, in _start_next_step_impl
	    log.err(e)
	--- <exception caught here> ---
	  File "/nix/store/3ix3c6m62qjj6abfxlkxz6nxp6dp1nnk-python3-3.12.7-env/lib/python3.12/site-packages/buildbot/process/build.py", line 622, in _start_next_step_impl
	    terminate = yield self.stepDone(results, step)  # interpret/merge results
	builtins.AssertionError: got None
```
I got this weird error when testing my internal buildbot instance, it shows up in the UI as so:

![image](https://github.com/user-attachments/assets/6536831f-43c4-4c44-ab36-25c46a1103af)

Which is weird since the Exception code isnt coming from any of the steps or sub-builds

**Comment by MagicRB** [comment]
Fixed by https://github.com/nix-community/buildbot-nix/pull/367
